### ISSUE TITLE
Gradle一直构建失败怎么办

### ISSUE THREAD

**Issue by JohnWayneHong** [FunnySaltyFish/FunnyTranslation#10]
![image](https://github.com/user-attachments/assets/09535c34-e23a-4d94-8aea-9d3aa176e90a)

**Comment by FunnySaltyFish** [comment]
虽然close了，但我也把回复搬运一遍，可能后面的朋友也需要

您好，由于项目里采用的依赖库较新，因而依赖库会优先使用国外仓库。最佳的解决方案是本地电脑配置科学上网，然后在Android Studio&Gradle配置代理；如果不行，你可以试着调整根目录下的 settings.gradle 和 translate/build.gradle 里面的仓库顺序，把国内的镜像（阿里源）调整到最上面
