### ISSUE TITLE
页面位置状态

### ISSUE THREAD

**Issue by valiantyan** [FunnySaltyFish/FunnyTranslation#3]
底部tab切换可以记住页面位置的状态吗？

**Comment by FunnySaltyFish** [comment]
理论上可以，参考谷歌给的 SaveableStateHolder 的 [demo](https://cs.android.com/androidx/platform/tools/dokka-devsite-plugin/+/master:testData/compose/samples/runtime/saveable/samples/SaveableStateHolderSamples.kt;l=42?q=androidx.compose.runtime.saveable.samples.SimpleNavigationWithSaveableStateSample%20) ，被 `rememberSaveable` 记住的值可以被保存。但我自己尝试了一下，插件页面那里的列表位置并没有被保存（有可能是因为我的数据是动态加载的，而数据本身只是被 `remember` 而不是 `rememberSaveable`？），具体您可以自己实践

*ps：由于不太清楚您是以用户角度还是开发者角度来问的，因此从开发者角度回答

**Comment by valiantyan** [comment]
fun NavHostController.navigateSingleTop(route: String, popUpToMain: Boolean = true){
    val navController = this
    navController.navigate(route) {
        //当底部导航导航到在非首页的页面时，执行手机的返回键 回到首页
        if (popUpToMain) {
            popUpTo(navController.graph.startDestinationId) {
                saveState = true
                //currentScreen = TranslateScreen.MainScreen
            }
        }
        //从名字就能看出来 跟activity的启动模式中的SingleTop模式一样 避免在栈顶创建多个实例
        launchSingleTop = true
        //切换状态的时候保存页面状态
        restoreState = true
    }
}
不知道为啥这里的代码没效果

**Comment by FunnySaltyFish** [comment]
我重新写了个小Demo，使用 
```kotlin
val lazyListState = rememberSaveable(saver = LazyListState.Saver) { LazyListState() }

LazyColumn(state = lazyListState) 
```
能够在导航时正确记住对应位置的
你可以运行 [这里](https://github.com/FunnySaltyFish/JetpackComposeStudy/blob/master/app/src/main/java/com/funny/compose/study/ui/nav/NavigationTest.kt) 的代码自行查看效果

**Comment by FunnySaltyFish** [comment]
看您没有回复，我先关闭 issue 喽，有问题欢迎继续交流
