### ISSUE TITLE
新导航栏问题反馈

### ISSUE THREAD

**Issue by Moriafly** [FunnySaltyFish/FunnyTranslation#5]
1. FunnyBottomNavigation moveTo 方法动画设定为 500 ms 时长并代码中 if (mValueAnimator!!.isRunning) return 导致若动画未执行完成用户无法切换页面
2. 新导航栏不适配 Android 无障碍

**Comment by FunnySaltyFish** [comment]
1. 是的，因为代码当时写的逻辑，如果中途点走了之前的动画状态就在半路，后续再点击就会出问题；另外，从动画角度来看，如果动画进行到一半再点击其他按钮，动画应该从当前位置换一条路，沿目标前进，这个就复杂一些，因此判断上就简单粗暴了
2. 确实，我曾经在某一版本发现了这个问题并尝试适配，不过写着写着写忘了（汗）。感谢提醒，之后的版本会尝试适配

**Comment by FunnySaltyFish** [comment]
新版本取消了底部导航栏。
