### ISSUE TITLE
侧边栏动画不统一

### ISSUE THREAD

**Issue by SOCK-MAGIC** [FunnySaltyFish/FunnyTranslation#7]
进入关于动画有一个向上顶，之后从右侧进来，而其他的项都没有向上的动画

**Comment by FunnySaltyFish** [comment]
收到，其实这几个 item 用的是同样的代码，造成这样的差异我估计可能是 “关于” 页面的 “关于 Text” 与原本 Drawer 的 “关于 Text” 中产生了类似 transition 的过渡效果，二者动画后重合。之后我会想办法解决的

**Comment by SOCK-MAGIC** [comment]
进入插件有点卡顿
建议固定翻译语种按钮的宽度
点击收藏按钮后弹出速度过快

**Comment by FunnySaltyFish** [comment]
好的，谢谢建议。第三点“点击收藏按钮后弹出速度过快”能麻烦详细描述下吗，我没太get到

**Comment by SOCK-MAGIC** [comment]
就是从下往上的速度太快，没有看到明显的过渡动画

**Comment by FunnySaltyFish** [comment]
了解，将会在下版本改进

**Comment by FunnySaltyFish** [comment]
这几个问题均在 v2.6.7 得到改进，此 issue 先关闭了。如果有其他问题或建议欢迎再讨论~
