### ISSUE TITLE
如何设置自己的翻译API

### ISSUE THREAD

**Issue by NianBroken** [FunnySaltyFish/FunnyTranslation#9]
目前我申请了有百度、腾讯的翻译API，但是在软件内没有找到设置自定义API的入口以及页面。

**Comment by FunnySaltyFish** [comment]
目前确实没有这个功能，现在的翻译请求实际上是在后端发出的，前端没有做这些调用的各种函数什么的。目前想实现使用自己的API只能自己写插件，技术难度较大。我也不确定是否要支持这样的功能

**Comment by NianBroken** [comment]
> 目前确实没有这个功能，现在的翻译请求实际上是在后端发出的，前端没有做这些调用的各种函数什么的。目前想实现使用自己的API只能自己写插件，技术难度较大。我也不确定是否要支持这样的功能

那么目前软件内的基础翻译功能是完全免费的嘛？

**Comment by FunnySaltyFish** [comment]
是的。目前（2024-02-27）除大模型外的引擎均免费使用
